name:                tx-poc-routing
version:             0.1.0.0
github:              "Diserasta/tx-poc-routing"
license:             BSD3
author:              "Sami Vassilev"
maintainer:          "diserasta@pm.me"
copyright:           "All Rights Reserved 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Diserasta/tx-poc-routing#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >=0.9.2 && <0.11
- text >= 1.2.3.0
- directory >= 1.3.0.0
- containers >= 0.6.0.0

default-extensions:
    - EmptyCase
    - ScopedTypeVariables
    - BangPatterns
    - OverloadedStrings

library:
  source-dirs: src

executables:
  tx-poc-routing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2
    dependencies:
    - tx-poc-routing

tests:
  tx-poc-routing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tx-poc-routing
